/*
 * Kadaster - Publiekrechtelijke beperkingen
 * De definitie van de Publiekrechtelijke beperkingen endpoints en components. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CategorieEnum
 */
@JsonAdapter(CategorieEnum.Adapter.class)
public enum CategorieEnum {
  
  DWANGSOM("dwangsom"),
  
  HANDHAVING("handhaving"),
  
  MONUMENT("monument");

  private String value;

  CategorieEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CategorieEnum fromValue(String value) {
    for (CategorieEnum b : CategorieEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CategorieEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final CategorieEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CategorieEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CategorieEnum.fromValue(value);
    }
  }
}

