/* 
 * Kadaster - Publiekrechtelijke beperkingen
 *
 * De definitie van de Publiekrechtelijke beperkingen endpoints en components. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines CategorieEnum
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CategorieEnum
    {
        /// <summary>
        /// Enum Dwangsom for value: dwangsom
        /// </summary>
        [EnumMember(Value = "dwangsom")]
        Dwangsom = 1,

        /// <summary>
        /// Enum Handhaving for value: handhaving
        /// </summary>
        [EnumMember(Value = "handhaving")]
        Handhaving = 2,

        /// <summary>
        /// Enum Monument for value: monument
        /// </summary>
        [EnumMember(Value = "monument")]
        Monument = 3

    }

}
