# language: nl

# Issue #1 #5 %8 #9
Functionaliteit: Als gemeente kunnen selecteren op de grondslag ven een publieke beperking
  De mogelijke typen grondslag van een publieke beperking zijn vastgelegd in de tabel AardAantekening.
  Voor iedere categorie grondlag die door gebruikers bevraagd moet kunnen worden zijn meerdere grondslag-codes van toepassing.
  Om de consumer-developer te vrijwaren van het interpreteren van de grondslagen-tabel (AardAantekening) is deze table hier uitgebreid met
  de categoriën zoals die door gebruikers specifiek bevraagd kunnen worden. 
  De vulling van die categoriën (en de toepassing daarvan in de queryparameter grondslagcategorie) word agile gedaan op basis van gebruikerswensen.

  Scenario: Zoeken van gemeentelijke monumenten
    Als publiekebeperkingen gezocht worden met ?grondslagcategorie=gemeentlijk_monument
    Dan bevat het antwoord publiekeBeperkingen waarvan grondslag.code voorkomt in [129,130,156,157,173, 174,175,357,358,365,366]


| 	Code	| 	Categorie           	 |        		 |        		 |              		 | 	                                                                                                                                             	 |
| 	129	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Besluit op basis van Monumentenwet 1988                                                                                                     	 |
| 	130	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Besluit op basis van Monumentenwet 1988 gedeeltelijk                                                                                        	 |
| 	131	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Aanschrijving woningwet                                                                                                                     	 |
| 	132	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Aanschrijving woningwet gedeeltelijk                                                                                                        	 |
| 	133	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Bouwgrond- en/of baatbelasting; inlichtingen bij de Gemeente                                                                                	 |
| 	134	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Bouwgrond- en/of baatbelasting gedeeltelijk; inlichtingen bij de Gemeente                                                                   	 |
| 	138	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Belemmeringenwet Privaatrecht                                                                                          	 |
| 	139	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Belemmeringenwet Privaatrecht (zie tekening)                                                                           	 |
| 	140	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Belemmeringenwet Privaatrecht (in onderzoek)                                                                           	 |
| 	141	  | 	                     	 | 	1-1-2000	 | 	31-1-2017	 | 	Aantekening PB	 | 	Kapverbod op basis van de Boswet                                                                                                            	 |
| 	144	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Belemmeringenwet Landsverdediging                                                                                      	 |
| 	145	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Belemmeringenwet Landsverdediging (zie tekening)                                                                       	 |
| 	146	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Belemmeringenwet Landsverdediging (in onderzoek)                                                                       	 |
| 	148	  | 	                     	 | 	10-3-2011	 | 	         	 | 	Aantekening PB	 | 	Exploitatieplan, Wet ruimtelijke ordening                                                                                                   	 |
| 	149	  | 	                     	 | 	10-3-2011	 | 	         	 | 	Aantekening PB	 | 	Exploitatieplan, Wet ruimtelijke ordening (Zie tekening)                                                                                    	 |
| 	150	  | 	                     	 | 	10-3-2011	 | 	         	 | 	Aantekening PB	 | 	Exploitatieplan, Wet ruimtelijke ordening (in onderzoek)                                                                                    	 |
| 	153	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Wet inzake de luchtverontreiniging                                                                                             	 |
| 	154	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Wet inzake de luchtverontreiniging (zie tekening)                                                                              	 |
| 	155	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Wet inzake de luchtverontreiniging (in onderzoek)                                                                              	 |
| 	156	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Gemeentelijk monument; inlichtingen bij de Gemeente                                                                                         	 |
| 	157	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Gemeentelijk monument gedeeltelijk; inlichtingen bij de Gemeente                                                                            	 |
| 	158	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Ontgrondingenwet                                                                                                               	 |
| 	159	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Ontgrondingenwet (zie tekening)                                                                                                	 |
| 	160	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Ontgrondingenwet (in onderzoek)                                                                                                	 |
| 	162	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Gedoogplicht ex. Art 10, lid 2, 12 of 12a Waterstaatswet 1900                                                                               	 |
| 	163	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Kapverbod ex. art.13 Boswet                                                                                                                 	 |
| 	164	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Kennisgeving, vordering, bevel of beschikking, Wet Bodembescherming                                                                         	 |
| 	165	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Kennisgeving, vordering, bevel of beschikking, Wet Bodembescherming (zie tekening)                                                          	 |
| 	166	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Kennisgeving, vordering, bevel of beschikking, Wet Bodembescherming (in onderzoek)                                                          	 |
| 	170	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Provinciaal monument                                                                                                                        	 |
| 	171	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Provinciaal monument (zie tekening)                                                                                                         	 |
| 	172	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Provinciaal monument (in onderzoek)                                                                                                         	 |
| 	173	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Monumentenwet 1988                                                                                                     	 |
| 	174	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Monumentenwet 1988 (zie tekening)                                                                                      	 |
| 	175	  | 	gemeentelijk_monument	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Monumentenwet 1988 (in onderzoek)                                                                                      	 |
| 	176	  | 	                     	 | 	1-1-2000	 | 	31-1-2017	 | 	Aantekening PB	 | 	Besluit op basis van natuurbeschermingswet 1998                                                                                             	 |
| 	177	  | 	                     	 | 	1-1-2000	 | 	31-1-2017	 | 	Aantekening PB	 | 	Besluit op basis van natuurbeschermingswet 1998 (zie tekening)                                                                              	 |
| 	178	  | 	                     	 | 	1-1-2000	 | 	31-1-2017	 | 	Aantekening PB	 | 	Besluit op basis van natuurbeschermingswet 1998 (in onderzoek)                                                                              	 |
| 	179	  | 	handhaving          	 | 	1-7-2010	 | 	         	 | 	Aantekening PB	 | 	Handhavingsbesluit Wabo                                                                                                                     	 |
| 	180	  | 	handhaving          	 | 	1-7-2010	 | 	         	 | 	Aantekening PB	 | 	Handhavingsbesluit Wabo (zie tekening)                                                                                                      	 |
| 	181	  | 	handhaving          	 | 	1-7-2010	 | 	         	 | 	Aantekening PB	 | 	Handhavingsbesluit Wabo (in onderzoek)                                                                                                      	 |
| 	184	  | 	                     	 | 	1-7-2010	 | 	         	 | 	Aantekening PB	 | 	Vorderingsbesluit Wabo                                                                                                                      	 |
| 	185	  | 	                     	 | 	1-7-2010	 | 	         	 | 	Aantekening PB	 | 	Vorderingsbesluit Wabo (zie tekening)                                                                                                       	 |
| 	186	  | 	                     	 | 	1-7-2010	 | 	         	 | 	Aantekening PB	 | 	Vorderingsbesluit Wabo (in onderzoek)                                                                                                       	 |
| 	194	  | 	                     	 | 	1-1-2000	 | 	1-1-2010	 | 	Aantekening PB	 | 	Voorkeursrecht gemeenten                                                                                                                    	 |
| 	196	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Wet agrarisch grondverkeer                                                                                             	 |
| 	197	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Wet agrarisch grondverkeer (zie tekening)                                                                              	 |
| 	198	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van Wet agrarisch grondverkeer (in onderzoek)                                                                              	 |
| 	201	  | 	                     	 | 	1-1-2000	 | 	1-9-2018	 | 	Aantekening PB	 | 	Besluit of bevel op basis van waterstaatswet 1900                                                                                           	 |
| 	203	  | 	                     	 | 	1-1-2000	 | 	1-9-2018	 | 	Aantekening PB	 | 	Besluit of bevel op basis van waterstaatswet 1900 (in onderzoek)                                                                            	 |
| 	204	  | 	                     	 | 	22-12-2009 | 	         	 | 	Aantekening PB	 | 	Bevel of gedoogplicht, Waterwet                                                                                                             	 |
| 	205	  | 	                     	 | 	22-12-2009 | 	         	 | 	Aantekening PB	 | 	Bevel of gedoogplicht, Waterwet (zie tekening)                                                                                              	 |
| 	206	  | 	                     	 | 	22-12-2009 | 	         	 | 	Aantekening PB	 | 	Bevel of gedoogplicht, Waterwet (in onderzoek)                                                                                              	 |
| 	207	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van woningwet                                                                                                              	 |
| 	208	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van woningwet (zie tekening)                                                                                               	 |
| 	209	  | 	                     	 | 	1-1-2000	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van woningwet (in onderzoek)                                                                                               	 |
| 	296	  | 	                     	 | 	1-7-2016	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht archeologisch onderzoek, Erfgoedwet                                                                                            	 |
| 	297	  | 	                     	 | 	1-7-2016	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht archeologisch onderzoek, Erfgoedwet (zie tekening)                                                                             	 |
| 	298	  | 	                     	 | 	1-7-2016	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht archeologisch onderzoek, Erfgoedwet (in onderzoek)                                                                             	 |
| 	307	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 9.9 Wet Natuurbescherming                                                                                      	 |
| 	308	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 9.9 Wet Natuurbescherming (Zie tekening)                                                                       	 |
| 	309	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 9.9 Wet Natuurbescherming (in onderzoek)                                                                       	 |
| 	310	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 9.1 Wet Natuurbescherming                                                                                      	 |
| 	311	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 9.1 Wet Natuurbescherming (Zie tekening)                                                                       	 |
| 	312	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 9.1 Wet Natuurbescherming (in onderzoek)                                                                       	 |
| 	313	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 2.1 Wet Natuurbescherming                                                                                      	 |
| 	314	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 2.1 Wet Natuurbescherming (Zie tekening)                                                                       	 |
| 	315	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 2.1 Wet Natuurbescherming (in onderzoek)                                                                       	 |
| 	316	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 2.11 Wet Natuurbescherming                                                                                     	 |
| 	317	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 2.11 Wet Natuurbescherming (Zie tekening)                                                                      	 |
| 	318	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 2.11 Wet Natuurbescherming (in onderzoek)                                                                      	 |
| 	319	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 4.2 Wet Natuurbescherming                                                                                      	 |
| 	320	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 4.2 Wet Natuurbescherming (Zie tekening)                                                                       	 |
| 	321	  | 	                     	 | 	1-2-2017	 | 	         	 | 	Aantekening PB	 | 	Besluit op basis van artikel 4.2 Wet Natuurbescherming (in onderzoek)                                                                       	 |
| 	339	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Belemmeringenwet Landsverdediging: Gedoogplicht                                                                                             	 |
| 	340	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Belemmeringenwet Landsverdediging: Gedoogplicht (in onderzoek)                                                                              	 |
| 	341	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Belemmeringenwet Privaatrecht: Gedoogplicht                                                                                                 	 |
| 	342	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Belemmeringenwet Privaatrecht: Gedoogplicht (in onderzoek)                                                                                  	 |
| 	343	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Belemmeringenwet Privaatrecht: Bevel verplaatsing werk                                                                                      	 |
| 	344	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Belemmeringenwet Privaatrecht: Bevel verplaatsing werk (in onderzoek)                                                                       	 |
| 	345	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Lasten en voorschriften uitvoering werk                                                                                         	 |
| 	346	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Lasten en voorschriften uitvoering werk (in onderzoek)                                                                          	 |
| 	347	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Gedoogplicht archeologisch onderzoek door minister OCW                                                                          	 |
| 	348	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Gedoogplicht archeologisch onderzoek door minister OCW (in onderzoek)                                                           	 |
| 	349	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Gedoogplicht archeologisch onderzoek door bestuursorgaan                                                                        	 |
| 	350	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Gedoogplicht archeologisch onderzoek door bestuursorgaan (in onderzoek)                                                         	 |
| 	351	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Toezending van een ontwerpbesluit door minister OCW                                                                             	 |
| 	352	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Toezending van een ontwerpbesluit door minister OCW (in onderzoek)                                                              	 |
| 	353	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Afschrift van een inschrijving door minister OCW                                                                                	 |
| 	354	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Erfgoedwet: Afschrift van een inschrijving door minister OCW (in onderzoek)                                                                 	 |
| 	355	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Besluit tot heffen van baatbelasting, Gemeentewet                                                                                           	 |
| 	356	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Besluit tot heffen van baatbelasting, Gemeentewet (in onderzoek)                                                                            	 |
| 	357	  | 	gemeentelijk_monument	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Besluit monument, Gemeentewet                                                                                                               	 |
| 	358	  | 	gemeentelijk_monument	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Besluit monument, Gemeentewet (in onderzoek)                                                                                                	 |
| 	359	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Ontgrondingenwet                                                                                                               	 |
| 	360	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gedoogplicht Ontgrondingenwet (in onderzoek)                                                                                                	 |
| 	361	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Sluiting van woning, lokaal of bijbehorend erf, Gemeentewet                                                                                 	 |
| 	362	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Sluiting van woning, lokaal of bijbehorend erf, Gemeentewet (in onderzoek)                                                                  	 |
| 	363	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Besluit tot heffen van bouwgrondbelasting, Gemeentewet                                                                                      	 |
| 	364	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Besluit tot heffen van bouwgrondbelasting, Gemeentewet (in onderzoek)                                                                       	 |
| 	365	  | 	gemeentelijk_monument	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Aanwijzing gemeentelijk monument (voorbescherming, aanwijzing, afschrift)                                                      	 |
| 	366	  | 	gemeentelijk_monument	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Aanwijzing gemeentelijk monument (voorbescherming, aanwijzing, afschrift) (in onderzoek)                                       	 |
| 	367	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Sluiting woning, lokaal of erf                                                                                                 	 |
| 	368	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Sluiting woning, lokaal of erf (in onderzoek)                                                                                  	 |
| 	369	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Bekostigingsbesluit baatbelasting                                                                                              	 |
| 	370	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Bekostigingsbesluit baatbelasting (in onderzoek)                                                                               	 |
| 	371	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Verordening baatbelasting                                                                                                      	 |
| 	372	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Gemeentewet: Verordening baatbelasting (in onderzoek)                                                                                       	 |
| 	373	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Huisvestingsverordening, splitsingsvergunningstelsel, Huisvestingswet 2014                                                                  	 |
| 	374	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Huisvestingsverordening, splitsingsvergunningstelsel, Huisvestingswet 2014 (in onderzoek)                                                   	 |
| 	375	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Huisvestingswet 2014: Vaststelling huisvestingsverordening inzake vergunningenstelsel splitsing                                             	 |
| 	376	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Huisvestingswet 2014: Vaststelling huisvestingsverordening inzake vergunningenstelsel splitsing (in onderzoek)                              	 |
| 	377	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Ontgrondingenwet: Gedoogplicht                                                                                                              	 |
| 	378	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Ontgrondingenwet: Gedoogplicht (in onderzoek)                                                                                               	 |
| 	379	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Opiumwet: Sluiting object                                                                                                                   	 |
| 	380	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Opiumwet: Sluiting object (in onderzoek)                                                                                                    	 |
| 	381	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Sluiting object, Opiumwet                                                                                                                   	 |
| 	382	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Sluiting object, Opiumwet (in onderzoek)                                                                                                    	 |
| 	383	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Provinciewet: Aanwijzing provinciaal monument (voornemen, aanwijzing, afschrift)                                                            	 |
| 	384	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Provinciewet: Aanwijzing provinciaal monument (voornemen, aanwijzing, afschrift) (in onderzoek)                                             	 |
| 	385	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Aanwijzing van gronden, Wet voorkeursrecht gemeenten                                                                                        	 |
| 	386	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Aanwijzing van gronden, Wet voorkeursrecht gemeenten (in onderzoek)                                                                         	 |
| 	387	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Voorstel tot dan wel voorlopige aanwijzing van gronden, Wet voorkeursrecht gemeenten                                                        	 |
| 	388	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Voorstel tot dan wel voorlopige aanwijzing van gronden, Wet voorkeursrecht gemeenten (in onderzoek)                                         	 |
| 	389	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Aanschrijving, Woningwet                                                                                                                    	 |
| 	390	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Aanschrijving, Woningwet (in onderzoek)                                                                                                     	 |
| 	391	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Beschikking geval ernstige verontreiniging en noodzaak spoedige sanering                                              	 |
| 	392	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Beschikking geval ernstige verontreiniging en noodzaak spoedige sanering (in onderzoek)                               	 |
| 	393	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Bevel ongewoon voorval                                                                                                	 |
| 	394	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Bevel ongewoon voorval (in onderzoek)                                                                                 	 |
| 	395	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Instemming verslag uniforme sanering                                                                                  	 |
| 	396	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Instemming verslag uniforme sanering (in onderzoek)                                                                   	 |
| 	397	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Instemming verslag                                                                                                    	 |
| 	398	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Instemming verslag (in onderzoek)                                                                                     	 |
| 	399	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Instemming nazorgplan                                                                                                 	 |
| 	400	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Instemming nazorgplan (in onderzoek)                                                                                  	 |
| 	401	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Bevel tijdelijke beveiligingsmaatregelen, onderzoek, beheren of saneren                                               	 |
| 	402	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Bevel tijdelijke beveiligingsmaatregelen, onderzoek, beheren of saneren (in onderzoek)                                	 |
| 	403	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Maatregel bevel                                                                                                       	 |
| 	404	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Maatregel bevel (in onderzoek)                                                                                        	 |
| 	405	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Vordering eigendom, gebruik of rechten                                                                                	 |
| 	406	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Vordering eigendom, gebruik of rechten (in onderzoek)                                                                 	 |
| 	407	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Uitoefening bevoegdheden vier grote steden of andere aan te wijzen gemeenten of plusregio                             	 |
| 	408	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet bodembescherming: Uitoefening bevoegdheden vier grote steden of andere aan te wijzen gemeenten of plusregio (in onderzoek)              	 |
| 	409	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Plicht tot het treffen van voorzieningen ten behoeve van eisen van welstand, Woningwet                                                      	 |
| 	410	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Plicht tot het treffen van voorzieningen ten behoeve van eisen van welstand, Woningwet (in onderzoek)                                       	 |
| 	411	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Plicht tot gebruik of beheer door derden, Woningwet                                                                                         	 |
| 	412	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Plicht tot gebruik of beheer door derden, Woningwet (in onderzoek)                                                                          	 |
| 	413	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet agrarisch grondverkeer: Aanwijzing landgoed                                                                                             	 |
| 	414	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet agrarisch grondverkeer: Aanwijzing landgoed (in onderzoek)                                                                              	 |
| 	415	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet agrarisch grondverkeer: Vestiging voorkeursrecht bij KB                                                                                 	 |
| 	416	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet agrarisch grondverkeer: Vestiging voorkeursrecht bij KB (in onderzoek)                                                                  	 |
| 	417	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Sluiting gebouw, open erf of terrein, Woningwet                                                                                             	 |
| 	418	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Sluiting gebouw, open erf of terrein, Woningwet (in onderzoek)                                                                              	 |
| 	419	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet inzake de luchtverontreiniging: Gedoogplicht meting luchtverontreiniging                                                                	 |
| 	420	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet inzake de luchtverontreiniging: Gedoogplicht meting luchtverontreiniging (in onderzoek)                                                 	 |
| 	421	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet natuurbescherming: Aanwijzing Natura2000-gebied                                                                                         	 |
| 	422	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet natuurbescherming: Aanwijzing Natura2000-gebied (in onderzoek)                                                                          	 |
| 	423	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet natuurbescherming: Aanwijzing bijzonder nationaal natuurgebied                                                                          	 |
| 	424	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet natuurbescherming: Aanwijzing bijzonder nationaal natuurgebied (in onderzoek)                                                           	 |
| 	425	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet natuurbescherming: Verbod vellen houtopstanden                                                                                          	 |
| 	426	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet natuurbescherming: Verbod vellen houtopstanden (in onderzoek)                                                                           	 |
| 	427	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet algemene bepalingen omgevingsrecht: Oplegging last onder bestuursdwang en/of dwangsom dat ook geldt voor rechtsopvolgers                	 |
| 	428	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet algemene bepalingen omgevingsrecht: Oplegging last onder bestuursdwang en/of dwangsom dat ook geldt voor rechtsopvolgers (in onderzoek) 	 |
| 	429	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet algemene bepalingen omgevingsrecht: Oplegging last onder bestuursdwang en/of dwangsom, niet geldend voor rechtsopvolgers                	 |
| 	430	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet algemene bepalingen omgevingsrecht: Oplegging last onder bestuursdwang en/of dwangsom, niet geldend voor rechtsopvolgers (in onderzoek) 	 |
| 	431	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet ruimtelijke ordening: Exploitatieplan                                                                                                   	 |
| 	432	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet ruimtelijke ordening: Exploitatieplan (in onderzoek)                                                                                    	 |
| 	433	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Waterwet: Bevel bij ongewoon voorval                                                                                                        	 |
| 	434	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Waterwet: Bevel bij ongewoon voorval (in onderzoek)                                                                                         	 |
| 	435	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Waterwet: Bevel verrichten onderzoek en tijdelijke beveiligingsmaatregelen                                                                  	 |
| 	436	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Waterwet: Bevel verrichten onderzoek en tijdelijke beveiligingsmaatregelen (in onderzoek)                                                   	 |
| 	437	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Waterwet: Gedoogplicht onderzoek of waterstaatswerk                                                                                         	 |
| 	438	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Waterwet: Gedoogplicht onderzoek of waterstaatswerk (in onderzoek)                                                                          	 |
| 	439	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Bestuursdwangbesluit of dwangsombesluit, Woningwet                                                                                          	 |
| 	440	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Bestuursdwangbesluit of dwangsombesluit, Woningwet (in onderzoek)                                                                           	 |
| 	441	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Plicht tot het treffen van voorzieningen, Woningwet                                                                                         	 |
| 	442	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Plicht tot het treffen van voorzieningen, Woningwet (in onderzoek)                                                                          	 |
| 	443	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet voorkeursrecht gemeenten: Besluit aanwijzing gronden                                                                                    	 |
| 	444	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet voorkeursrecht gemeenten: Besluit aanwijzing gronden (in onderzoek)                                                                     	 |
| 	445	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet voorkeursrecht gemeenten: Voorstel aanwijzing gronden                                                                                   	 |
| 	446	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Wet voorkeursrecht gemeenten: Voorstel aanwijzing gronden (in onderzoek)                                                                    	 |
| 	447	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Plicht treffen voorzieningen tot niveau nieuwbouw                                                                                	 |
| 	448	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Plicht treffen voorzieningen tot niveau nieuwbouw (in onderzoek)                                                                 	 |
| 	449	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Plicht treffen voorzieningen welstand                                                                                            	 |
| 	450	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Plicht treffen voorzieningen welstand (in onderzoek)                                                                             	 |
| 	451	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Plicht ingebruikgeving object aan een ander                                                                                      	 |
| 	452	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Plicht ingebruikgeving object aan een ander (in onderzoek)                                                                       	 |
| 	453	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Sluiting object                                                                                                                  	 |
| 	454	  | 	                     	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Sluiting object (in onderzoek)                                                                                                   	 |
| 	455	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Oplegging last onder bestuursdwang en/of dwangsom dat ook geldt voor rechtsopvolgers                                             	 |
| 	456	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Oplegging last onder bestuursdwang en/of dwangsom dat ook geldt voor rechtsopvolgers (in onderzoek)                              	 |
| 	457	  | 	dwangsom             	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Oplegging last onder bestuursdwang en/of dwangsom niet geldend voor rechtsopvolgers                                              	 |
| 	458	  | 	dwangsom            	 | 	1-1-2020	 | 	         	 | 	Aantekening PB	 | 	Woningwet: Oplegging last onder bestuursdwang en/of dwangsom niet geldend voor rechtsopvolgers (in onderzoek)                               	 |
