# language: nl

# Issue #1 #5 #8 #9
Functionaliteit: Als gemeente kunnen selecteren op een type grondslag van een publieke beperking
  De mogelijke typen grondslag van een publieke beperking zijn vastgelegd in de tabel [Grondslag BRK-PB](https://developer.kadaster.nl/schemas/waardelijsten/GrondslagBRK-PB/index.html).
  Voor ieder type publieke beperking is aangegeven met welke grondslagen die gerelateerd is.
  Om de consumer-developer te vrijwaren van het interpreteren van de grondslagen-tabel (GrondslagBRK-PB) is deze tabel in deze feature uitgebreid met
  de typen zoals die door gebruikers specifiek bevraagd kunnen worden.
  De vulling van die typen (en de toepassing daarvan in de queryparameter "type") word agile gedaan op basis van gebruikerswensen.

  Scenario: Zoeken van gemeentelijke monumenten
    Als publieke beperkingen gezocht worden met ?type=gemeentelijkmonument
    Dan bevat het antwoord publiekeBeperkingen waarvan grondslag.code voorkomt in [129,130,156,157,173, 174,175,357,358,365,366]

In de onderstaande tabel zijn zowel waarde als toelichtingen afgekapt i.v.m. de leesbaarheid. Voor het presenteren van gegevens wordt verwezen naar de tabel [Grondslag BRK-PB](https://developer.kadaster.nl/schemas/waardelijsten/GrondslagBRK-PB/index.html).


    | 	Code | Type                  | 	Waarde	                                                                                 | 	DatumVanaf | 	DatumTot	 | 	Toelichting	 |
    | 	GG	 | gemeentelijkmonument  |  Aanwijzing gemeentelijk monument (voorbescherming, aanwijzing, afschrift)	               | 	1-1-1900	 | 	1-1-2020	 | 	Gemeentewet: (artikel 149) besluit krachtens gemeentelijke verordening tot aanwijzing van een onroerende zaak als beschermd monument, voor zover geen beperkingenbesluit als bedoeld in artikel 1, onderdeel b, onder 6°, van de wet is dan wel moet worden genomen	 |
    | 	GWA	 | gemeentelijkmonument  |  Gemeentewet: Aanwijzing gemeentelijk monument (voorbescherming, aanwijzing, afschrift)	 | 	1-1-2020	 | 		         | 	Gemeentewet: (artikel 149) besluit krachtens gemeentelijke verordening tot aanwijzing van een onroerende zaak als beschermd monument, voor zover geen beperkingenbesluit als bedoeld in artikel 1, onderdeel b, onder 6°, van de wet is dan wel moet worden genomen	 |
    | 	GS	 |                       | 	Sluiting woning, lokaal of erf	                                                         | 	1-1-1900	 | 	1-1-2020	 | 	Gemeentewet: (artikel 174a) besluit van de burgemeester tot het sluiten van een woning, een niet voor het publiek toegankelijk lokaal of een bij die woning of dat lokaal behorend erf	 |
    | 	GWB	 | 	                     | 	Gemeentewet: Sluiting woning, lokaal of erf	                                             | 	1-1-2020	 |         		 | 	Gemeentewet: (artikel 174a) besluit van de burgemeester tot het sluiten van een woning, een niet voor het publiek toegankelijk lokaal of een bij die woning of dat lokaal behorend erf	 |
    | 	GB	 | 	                     | 	Bekostigingsbesluit / verordening baatbelasting	                                         | 	1-1-1995	 | 	1-1-2020	 | 	Gemeentewet: (artikel 222, zoals dit artikel vanaf 1 januari 1995 luidt) gemeentelijk bekostigingsbesluit strekkend tot het heffen van een gemeentelijke baatbelasting krachtens verordening	 |
    | 	GWC	 | 	                     | 	Gemeentewet: Bekostigingsbesluit baatbelasting                                         	 | 	1-1-2020	 |        		 | 	Gemeentewet: (artikel 222, zoals dit artikel vanaf 1 januari 1995 luidt) gemeentelijk bekostigingsbesluit strekkend tot het heffen van een gemeentelijke baatbelasting krachtens verordening	 |
    | 	GWD	 | 	                     | 	Gemeentewet: Verordening baatbelasting                                                 	 | 	1-1-2020	 | 		         | 	Gemeentewet: (artikel 222, zoals dit artikel vanaf 1 januari 1995 luidt, juncto artikel 216) vaststelling verordening tot het heffen van een gemeentelijke baatbelasting	 |
    | 	GU	 | 	                     | 	Bekostigingsbesluit / verordening bouwgrondbelasting	                                   | 	1-1-1900	 | 	1-1-2020	 | 	Gemeentewet: (artikel 222, zoals dit artikel tot 1 januari 1995 heeft geluid) gemeentelijk bekostigingsbesluit strekkend tot het heffen van een gemeentelijke bouwgrondbelasting krachtens verordening	 |
    | 	MP	 | 	                     | 	Provinciewet	                                                                           | 	1-1-1900	 | 	1-1-2020	 | 	Provinciewet	 |
    | 	PVA	 | 	                     | 	Provinciewet: Aanwijzing provinciaal monument (voornemen, aanwijzing, afschrift)      	 | 	1-1-2020	 | 		         | 	Provinciewet: (artikel 145) besluit krachtens provinciale verordening tot aanwijzing van een onroerende zaak als beschermd monument, voor zover geen beperkingenbesluit als bedoeld in artikel 1, onderdeel b, onder 6°, van de wet is dan wel moet worden genomen	 |
    | 	BL	 | 	                     | 	Gedoogplicht landsverdediging	                                                           | 	1-1-1900	 | 	1-1-2020	 | 	Belemmeringenwet Landsverdediging: (artikelen 6 en 7) een door of namens de Minister van Defensie of de Minister van Binnenlandse Zaken en Koninkrijksrelaties opgelegde gedoogplicht voor een ieder inzake het duurzaam of tijdelijk gebruik van .... |
    | 	BLA	 | 	                     | 	Belemmeringenwet Landsverdediging: Gedoogplicht	                                         | 	1-1-2020	 | 		         | 	Belemmeringenwet Landsverdediging: (artikelen 6 en 7) een door of namens de Minister van Defensie of de Minister van Binnenlandse Zaken en Koninkrijksrelaties opgelegde gedoogplicht voor een ieder inzake het duurzaam of tijdelijk gebruik van .... |
    | 	WN	 | 	                     | 	Aanwijzing Natura2000-gebied	                                                           | 	1-1-1900	 | 	1-1-2020	 | 	Wet natuurbescherming: (artikel 2.1, eerste lid) aanwijzing door de Minister van Economische Zaken en Klimaat van een gebied als Natura 2000-gebied	 |
    | 	WNA	 | 	                     | 	Wet natuurbescherming: Aanwijzing Natura2000-gebied	                                     | 	1-1-2020	 | 	        	 | 	Wet natuurbescherming: (artikel 2.1, eerste lid) aanwijzing door de Minister van Economische Zaken en Klimaat van een gebied als Natura 2000-gebied	 |
    | 	WX	 | 	                     | 	Aanwijzing bijzonder nationaal natuurgebied	                                             | 	1-1-1900	 | 	1-1-2020	 | 	Wet natuurbescherming: (artikel 2.11, eerste lid) aanwijzing door de Minister van Economische Zaken en Klimaat van een gebied als bijzonder nationaal natuurgebied	 |
    | 	WNB	 | 	                     | 	Wet natuurbescherming: Aanwijzing bijzonder nationaal natuurgebied	                     | 	1-1-2020	 | 	        	 | 	Wet natuurbescherming: (artikel 2.11, eerste lid) aanwijzing door de Minister van Economische Zaken en Klimaat van een gebied als bijzonder nationaal natuurgebied	 |
    | 	WY	 | 	                     | 	Verbod vellen houtopstanden	                                                             | 	1-1-1900	 | 	1-1-2020	 | 	Wet natuurbescherming: (artikel 4.2, derde lid) bij besluit van gedeputeerde staten of de Minister van Economische Zaken en Klimaat (krachtens artikel 1.3, vijfde lid) opgelegd verbod op het vellen van houtopstanden	 |
    | 	WNC	 | 	                     | 	Wet natuurbescherming: Verbod vellen houtopstanden	                                     | 	1-1-2020	 | 		         | 	Wet natuurbescherming: (artikel 4.2, derde lid) bij besluit van gedeputeerde staten of de Minister van Economische Zaken en Klimaat (krachtens artikel 1.3, vijfde lid) opgelegd verbod op het vellen van houtopstanden	 |
    | 	WA	 | 	                     | 	Wet agrarisch grondverkeer	                                                             | 	1-1-1900	 | 	1-1-2020	 | 	Wet agrarisch grondverkeer	 |
    | 	WGA	 | 	                     | 	Wet agrarisch grondverkeer: Aanwijzing landgoed	                                         | 	1-1-2020	 |         		 | 	Wet agrarisch grondverkeer: (artikel 7) aanwijzing als landgoed door de Minister van Onderwijs, Cultuur en Wetenschap in overeenstemming met de Minister van Landbouw, Natuur en Voedselkwaliteit	 |
    | 	WGB	 | 	                     | 	Wet agrarisch grondverkeer: Vestiging voorkeursrecht bij KB	                             | 	1-1-2020	 | 		         | 	Wet agrarisch grondverkeer: (artikel 37, derde lid) vestiging van een voorkeursrecht bij koninklijk besluit	 |
    | 	EW	 | 	                     | 	Erfgoedwet                                                                            	 | 	1-1-1900	 | 	1-1-2020	 | 	Erfgoedwet	 |
    | 	EWA	 | 	                     | 	Erfgoedwet: Lasten en voorschriften uitvoering werk	                                     | 	1-1-2020	 | 	         	 | 	Erfgoedwet: (artikel 9.1, eerste lid, van de Erfgoedwet in samenhang met artikel 56 van de Monumentenwet 1988 zoals die wet luidde voor inwerkingtreding van de Erfgoedwet) voorschriften van de Minister van Onderwijs, Cultuur en Wetenschap met betrekking tot de uitvoering van een werk dan wel een last tot stillegging van een werk	 |
    | 	EWB	 | 	                     | 	Erfgoedwet: Gedoogplicht archeologisch onderzoek door minister OCW                     	 | 	1-1-2020	 | 	        	 | 	Erfgoedwet: (artikel 9.1, eerste lid, van de Erfgoedwet in samenhang met artikel 57, eerste lid, van de Monumentenwet 1988 zoals die wet luidde voor inwerkingtreding van de Erfgoedwet) door de Minister van Onderwijs, Cultuur en Wetenschap opgelegde gedoogplicht inhoudend ....	 |
    | 	EWC	 | 	                     | 	Erfgoedwet: Gedoogplicht archeologisch onderzoek door bestuursorgaan	                   | 	1-1-2020	 |        		 | 	Erfgoedwet: (artikel 9.1, eerste lid, van de Erfgoedwet in samenhang met artikel 57, tweede lid, van de Monumentenwet 1988 zoals die wet luidde voor inwerkingtreding van de Erfgoedwet) door een bestuursorgaan ter voorbereiding of uitvoering van een bestemmingsplan als bedoeld in artikel 3.1 .... |
    | 	EWD	 | 	                     | 	Erfgoedwet: Toezending van een ontwerpbesluit door minister OCW	                         | 	1-1-2020	 |        		 | 	Erfgoedwet: (wet artikel 1, onderdeel b, sub 2o) een toezending van een ontwerpbesluit door Onze Minister van Onderwijs, Cultuur en Wetenschap als bedoeld in artikel 3.2, eerste lid, van de Erfgoedwet, in samenhang met artikel 3:13, eerste lid, van de Algemene wet bestuursrecht	 |
    | 	EWE	 | 	                     | 	Erfgoedwet: Afschrift van een inschrijving door minister OCW	                           | 	1-1-2020	 |        		 | 	Erfgoedwet: (wet artikel 1, onderdeel b, sub 3o) een afschrift van een inschrijving door Onze Minister van Onderwijs, Cultuur en Wetenschap van een als rijksmonument aangewezen monument of archeologisch monument in het rijksmonumentenregister, bedoeld in artikel 1.1 van de Erfgoedwet	 |
    | 	MW	 | 	                     | 	Rijksmonumenten op basis van de Monumentenwet	                                           | 	1-1-1900	 | 	1-1-2020	 | 	Rijksmonumenten op basis van de Monumentenwet	 |
    | 	BG	 | 	                     | 	Belemmeringenwet Privaatrecht	                                                           | 	1-1-1900	 | 	1-1-2020	 | 	Belemmeringenwet Privaatrecht	 |
    | 	BPA	 | 	                     | 	Belemmeringenwet Privaatrecht: Gedoogplicht	                                             | 	1-1-2020	 | 	        	 | 	Belemmeringenwet Privaatrecht: (artikelen 2, vijfde lid, en 3, tweede lid) door de Minister van Infrastructuur en Waterstaat opgelegde gedoogplichten	 |
    | 	BPB	 | 	                     | 	Belemmeringenwet Privaatrecht: Bevel verplaatsing werk	                                 | 	1-1-2020	 |         		 | 	Belemmeringenwet Privaatrecht: (artikel 5) bevel van de Minister van Infrastructuur en Waterstaat tot verplaatsing van een werk	 |
    | 	GO	 | 	                     | 	Ontgrondingenwet	                                                                       | 	1-1-1900	 | 	1-1-2020	 | 	Ontgrondingenwet	 |
    | 	OGA	 | 	                     | 	Ontgrondingenwet: Gedoogplicht	                                                         | 	1-1-2020	 |        		 | 	Ontgrondingenwet: (artikel 21g) door de Minister van Infrastructuur en Waterstaat of gedeputeerde staten opgelegde gedoogplicht	 |
    | 	WT	 | 	                     | 	Waterwet	                                                                               | 	1-1-1900	 | 	1-1-2020	 | 	Waterwet	 |
    | 	WTA	 | 	                     | 	Waterwet: Bevel bij ongewoon voorval	                                                   | 	1-1-2020	 | 	         	 | 	Waterwet: (artikel 5.15 juncto artikel 30 van de Wet bodembescherming) maatregel (bevel) van de beheerder bij een ongewoon voorval	 |
    | 	WTB	 | 	                     | 	Waterwet: Bevel verrichten onderzoek en tijdelijke beveiligingsmaatregelen	             | 	1-1-2020	 |        		 | 	Waterwet: (artikel 5.16) bevel van de beheerder tot het verrichten van onderzoek en tot het treffen van tijdelijke beveiligingsmaatregelen	 |
    | 	WTC	 | 	                     | 	Waterwet: Gedoogplicht onderzoek of waterstaatswerk	                                     | 	1-1-2020	 |        		 | 	Waterwet: (artikelen 5.21 en 5.24) door de beheerder opgelegde gedoogplichten	 |
    | 	OS	 |	                     |  Opiumwet	                                                                               | 	1-1-1900	 | 	1-1-2020	 | 	Opiumwet	 |
    | 	OPA	 | 	                     | 	Opiumwet: Sluiting object	                                                               | 	1-1-2020	 |         		 | 	Opiumwet: (artikel 13b, eerste lid) besluit van de burgemeester tot oplegging van een last onder bestuursdwang, indien dat besluit strekt tot sluiting van het betreffende object	 |
    | 	HS	 | 	                     | 	Huisvestingswet 2014	                                                                   | 	1-1-1900	 | 	1-1-2020	 | 	Huisvestingswet 2014	 |
    | 	HVA	 | 	                     | 	Huisvestingswet 2014: Vaststelling huisvestingsverordening inzake vergunningenstelsel ...| 	1-1-2020	 | 		         | 	Huisvestingswet 2014: (artikelen 4 en 22) vaststelling huisvestingsverordening (aanwijzing categorie gebouwen waarvoor het in artikel 22 bedoelde vergunningenstelsel inzake splitsing in appartementsrechten geldt)	 |
    | 	OH	 | 	                     | 	Wet algemene bepalingen omgevingsrecht	                                                 | 	1-1-1900	 | 	1-1-2020	 | 	Wet algemene bepalingen omgevingsrecht	 |
    | 	WOA	 | dwangsom              | 	Wet algemene bepalingen omgevingsrecht: Oplegging last onder bestuursdwang en/of ...     | 	1-1-2020	 | 	        	 | 	Wet algemene bepalingen omgevingsrecht: (artikel 5.2 juncto het bepaalde bij of krachtens de Wet algemene bepalingen omgevingsrecht en artikel 5.18) besluit tot oplegging van een last onder bestuursdwang, respectievelijk besluit tot oplegging van een last onder dwangsom van het bevoegd gezag, gericht op nalevin... 	 |
    | 	WOB	 | dwangsom              | 	Wet algemene bepalingen omgevingsrecht: Oplegging last onder bestuursdwang en/of ...     | 	1-1-2020	 | 	        	 | 	Wet algemene bepalingen omgevingsrecht: (artikel 5.24 juncto het bepaalde bij of krachtens de Wet algemene bepalingen omgevingsrecht) vorderingsbesluit van de Minister van Binnenlandse Zaken en Koninkrijksrelaties tot oplegging van een last onder bestuursdwang, respectievelijk last onder dwangsom door het ...  |
    | 	KW	 | 	                     | 	Wet bodembescherming	                                                                   | 	1-1-1900	 | 	1-1-2020	 | 	Wet bodembescherming	 |
    | 	WBA	 | 	                     | 	Wet bodembescherming: Beschikking geval ernstige verontreiniging en noodzaak ...         | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 29, eerste lid, juncto artikel 37, eerste lid) beschikking van gedeputeerde staten dat sprake is van een geval van ernstige verontreiniging, al dan niet met zodanige risico’s dat spoedige sanering noodzakelijk is	 |
    | 	WBB	 | 	                     | 	Wet bodembescherming: Bevel ongewoon voorval	                                           | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 30 juncto artikel 31) maatregel (bevel) van gedeputeerde staten (artikel 30) (eventueel vooruitlopend daarop: van de commissaris van de Koning (artikel 31)) bij een ongewoon voorval	 |
    | 	WBC	 | 	                     | 	Wet bodembescherming: Instemming verslag uniforme sanering	                             | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 39b juncto artikel 14 van het Besluit uniforme saneringen) beschikking van gedeputeerde staten houdende instemming met het verslag van een uniforme sanering als bedoeld in artikel 39b, indien sprake is geweest van de saneringsaanpak, bedoeld in artikel 3, eerste lid, ... 	 |
    | 	WBD	 | 	                     | 	Wet bodembescherming: Instemming verslag	                                               | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 39c, tweede lid) beschikking van gedeputeerde staten, houdende instemming met het verslag, bedoeld in artikel 39c, eerste lid, indien in dat verslag beperkingen in het gebruik van de bodem zijn beschreven	 |
    | 	WBE	 | 	                     | 	Wet bodembescherming: Instemming nazorgplan	                                             | 	1-1-2020	 |         		 | 	Wet bodembescherming: (artikel 39d, derde lid) beschikking van gedeputeerde staten, houdende instemming met het nazorgplan	 |
    | 	WBF	 | 	                     | 	Wet bodembescherming: Bevel tijdelijke beveiligingsmaatregelen, onderzoek, ...        	 | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 43) bevel van gedeputeerde staten tot tijdelijke beveiligingsmaatregelen, tot het verrichten van onderzoek, tot het beheren of saneren van de bodem en overige daar genoemde beschikkingen	 |
    | 	WBG	 | 	                     | 	Wet bodembescherming: Maatregel bevel	                                                   | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 49) maatregel (bevel) van gedeputeerde staten	 |
    | 	WBH	 | 	                     | 	Wet bodembescherming: Vordering eigendom, gebruik of rechten	                           | 	1-1-2020	 |        		 | 	Wet bodembescherming: (artikel 50) vordering van eigendom of gebruik van onroerende zaken, of van beperkte rechten waaraan onroerende zaken zijn onderworpen, dan wel het gebruik daarvan, door de Minister van Infrastructuur en Waterstaat	 |
    | 	WBI	 | 	                     | 	Wet bodembescherming: Uitoefening bevoegdheden vier grote steden of ...                	 | 	1-1-2020	 | 	        	 | 	Wet bodembescherming: (artikel 88) uitoefening bevoegdheden als bedoeld in de artikelen 29, 30, 31, 37, 39b, 39c, 39d, 43 en 49, door de gemeenten Amsterdam, ’s-Gravenhage, Rotterdam en Utrecht of een andere gemeente die is aangewezen op grond van artikel 88, zevende lid, dan wel door een plusregio als bedoeld in artikel 88, tweede lid	 |
    | 	GL	 | 	                     | 	Wet inzake de luchtverontreiniging	                                                     | 	1-1-1900	 | 	1-1-2020	 | 	Wet inzake de luchtverontreiniging	 |
    | 	WLA	 | 	                     | 	Wet inzake de luchtverontreiniging: Gedoogplicht meting luchtverontreiniging	           | 	1-1-2020	 |        		 | 	Wet inzake de luchtverontreiniging: (artikel 60) door de Minister van Infrastructuur en Waterstaat opgelegde gedoogplicht voor zover deze betreft het gebruik maken van onroerende zaken ten behoeve van het bepalen van luchtverontreiniging	 |
    | 	EP	 |	                     |  Wet ruimtelijke ordening	                                                               | 	1-1-1900	 | 	1-1-2020	 | 	Wet ruimtelijke ordening	 |
    | 	WRA	 | 	                     | 	Wet ruimtelijke ordening: Exploitatieplan	                                               | 	1-1-2020	 |        		 | 	Wet ruimtelijke ordening: (artikel 6.12 juncto artikel 6.25) door het bevoegd gezag, bedoeld in artikel 6.12 dan wel 6.25, vastgesteld exploitatieplan, voor zover op grond daarvan de verplichting bestaat aan een omgevingsvergunning een voorschrift tot betaling van een exploitatiebijdrage te verbinden	 |
    | 	VI	 | 	                     | 	Besluit aanwijzing gronden                                                             	 | 	1-1-1900	 | 	1-1-2020	 | 	Wet voorkeursrecht gemeenten: (artikel 2, in samenhang met artikel 3, 4 of 5) aanwijzing van gronden bij besluit van de gemeenteraad	 |
    | 	WVA	 | 	                     | 	Wet voorkeursrecht gemeenten: Besluit aanwijzing gronden	                               | 	1-1-2020	 |        		 | 	Wet voorkeursrecht gemeenten: (artikel 2, in samenhang met artikel 3, 4 of 5) aanwijzing van gronden bij besluit van de gemeenteraad	 |
    | 	VV	 | 	                     | 	Voorstel aanwijzing gronden	                                                             | 	1-1-1900	 | 	1-1-2020	 | 	Wet voorkeursrecht gemeenten: (artikel 6) voorlopige aanwijzing van gronden bij besluit van burgemeester en wethouders	 |
    | 	WVB	 | 	                     | 	Wet voorkeursrecht gemeenten: Voorstel aanwijzing gronden	                               | 	1-1-2020	 | 	        	 | 	Wet voorkeursrecht gemeenten: (artikel 6) voorlopige aanwijzing van gronden bij besluit van burgemeester en wethouders	 |
    | 	WV	 | 	                     | 	Plicht treffen voorzieningen tot niveau nieuwbouw	                                       | 	1-1-1900	 | 	1-1-2020	 | 	Woningwet: (artikel 13) door het bevoegd gezag opgelegde plicht tot het treffen van voorzieningen tot op ten hoogste nieuwbouwniveau met betrekking tot een bestaand gebouw of ander bouwwerk, niet zijnde een gebouw	 |
    | 	WWA	 | 	                     | 	Woningwet: Plicht treffen voorzieningen tot niveau nieuwbouw                          	 | 	1-1-2020	 | 		         | 	Woningwet: (artikel 13) door het bevoegd gezag opgelegde plicht tot het treffen van voorzieningen tot op ten hoogste nieuwbouwniveau met betrekking tot een bestaand gebouw of ander bouwwerk, niet zijnde een gebouw	 |
    | 	WE	 | 	                     | 	Plicht treffen voorzieningen welstand	                                                   | 	1-1-1900	 | 	1-1-2020	 | 	Woningwet: (artikel 13a) door het bevoegd gezag opgelegde plicht tot het treffen van voorzieningen om een bouwwerk in overeenstemming te brengen met redelijke eisen van welstand	 |
    | 	WWB	 | 	                     | 	Woningwet: Plicht treffen voorzieningen welstand	                                       | 	1-1-2020	 | 	         	 | 	Woningwet: (artikel 13a) door het bevoegd gezag opgelegde plicht tot het treffen van voorzieningen om een bouwwerk in overeenstemming te brengen met redelijke eisen van welstand	 |
    | 	WG	 | 	                     | 	Plicht ingebruikgeving object aan een ander	                                             | 	1-1-1900	 | 	1-1-2020	 | 	Woningwet: (artikel 13b) door het bevoegd gezag opgelegde plicht om een in dat artikel genoemd object aan een ander in gebruik of beheer te geven	 |
    | 	WWC	 | 	                     | 	Woningwet: Plicht ingebruikgeving object aan een ander	                                 | 	1-1-2020	 | 	        	 | 	Woningwet: (artikel 13b) door het bevoegd gezag opgelegde plicht om een in dat artikel genoemd object aan een ander in gebruik of beheer te geven	 |
    | 	WWD	 | 	                     | 	Woningwet: Sluiting object	                                                             | 	1-1-2020	 | 	        	 | 	Woningwet: (artikel 17) besluit van het bevoegd gezag tot het sluiten van een gebouw, open erf of terrein	 |
    | 	WI	 | 	                     | 	Sluiting object	                                                                         | 	1-1-1900	 | 	1-1-2020	 | 	Woningwet: (artikel 17) besluit van het bevoegd gezag tot het sluiten van een gebouw, open erf of terrein	 |
    | 	WU	 | dwangsom  	           | 	Oplegging last onder bestuursdwang en/of dwangsom dat ook geldt voor rechtsopvolgers	   | 	1-1-1900	 | 	1-1-2020	 | 	Woningwet: (artikel 92 juncto de hoofdstukken I tot en met III van de Woningwet en artikel 5.18 van de Wet algemene bepalingen omgevingsrecht) besluit tot oplegging van een last onder bestuursdwang, respectievelijk besluit tot oplegging van een last onder dwangsom van het bevoegd gezag, ... 	 |
    | 	WWF	 | dwangsom  	           | 	Woningwet: Oplegging last onder bestuursdwang en/of dwangsom niet geldend ...         	 | 	1-1-2020	 |        		 | 	Woningwet: (artikel 92 juncto de hoofdstukken I tot en met III van de Woningwet en artikel 5.24 van de Wet algemene bepalingen omgevingsrecht) vorderingsbesluit van de Minister van Binnenlandse Zaken en Koninkrijksrelaties tot oplegging van een last onder bestuursdwang, respectievelijk ... 	 |
    | 	WWE	 | dwangsom  	           | 	Woningwet: Oplegging last onder bestuursdwang en/of dwangsom dat ook geldt ...           | 	1-1-2020	 | 	        	 | 	Woningwet: (artikel 92 juncto de hoofdstukken I tot en met III van de Woningwet en artikel 5.18 van de Wet algemene bepalingen omgevingsrecht) besluit tot oplegging van een last onder bestuursdwang, respectievelijk besluit tot oplegging van een last onder dwangsom van het bevoegd gezag, ... |
    | 	WW	 | 	                     | 	Besluit op basis van woningwet	                                                         | 	1-1-1900	 | 	1-1-2020	 | 	Besluit op basis van woningwet	 |
    | 	BF	 | 	                     | 	Beschermde leefomgeving Flora- en Faunawet                                            	 | 	1-1-1900	 | 	1-1-2020	 | 	Beschermde leefomgeving Flora- en Faunawet	 |
    | 	BK	 | 	                     | 	Besluit op basis van artikel 9.9 Wet Natuurbescherming	                                 | 	1-1-1900	 | 	1-1-2020	 | 	Besluit op basis van artikel 9.9 Wet Natuurbescherming	 |
    | 	LW	 | 	                     | 	Verbod op basis van de Luchtvaartwet	                                                   | 	1-1-1900	 | 	1-1-2020	 | 	Verbod op basis van de Luchtvaartwet	 |
    | 	NM	 | 	                     | 	Natuurbeschermingswet 1998 op basis van de Wet Natuurbescherming	                       | 	1-1-1900	 | 	1-1-2020	 | 	Natuurbeschermingswet 1998 op basis van de Wet Natuurbescherming	 |
    | 	OV	 | 	                     | 	Vorderingsbesluit	                                                                       | 	1-1-1900	 | 	1-1-2020	 | 	Vorderingsbesluit	 |
    | 	PG	 | 	                     | 	Gedoogplicht op basis van Grondwaterwet	                                                 | 	1-1-1900	 | 	1-1-2020	 | 	Gedoogplicht op basis van Grondwaterwet	 |
    | 	WS	 | 	                     | 	Besluit of bevel op basis van waterstaatswet 1900	                                       | 	1-1-1900	 | 	1-1-2020	 | 	Besluit of bevel op basis van waterstaatswet 1900	 |
